import googlemaps
from datetime import datetime

generieke_kolomnamen = {'BRIN NUMMER': "Brin",
                        'VESTIGINGSNUMMER': "Brinvolgnummer",
                        'INSTELLINGSNAAM VESTIGING': "NaamInstelling",
                        'GEMEENTENAAM': 'Gemeente',
                        'ONDERWIJSTYPE VO': "Onderwijstype",
                        'INSPECTIECODE': 'CodeInspectie',
                        'OPLEIDINGSNAAM': 'NaamOpleiding',
                        'onderwijssoort': 'Onderwijssoort',
                        'BRIN': 'Brin',
                        'brin_naam': 'NaamInstelling',
                        'brin_adres': 'Adres',
                        'brin_pc': 'Postcode',
                        'brin_plaats': 'Plaats',
                        'brin_provincie': 'Provincie',
                        'brin_gemnr': 'Gemeentenummer',
                        'brin_gemeente': 'Gemeente',
                        'bgnummer': 'BevoegdGezag',
                        'bg_naam': 'NaamBevoegdGezag',
                        'bg_adres': 'AdresBevoegdGezag',
                        'bg_pc': "PostcodeBevoegdGezag",
                        'bg_plaats': "PlaatsBevoegdGezag",
                        'bg_provincie': "ProvincieBevoegdGezag",
                        'bg_gemnr': 'GemeenteNummerBevoegdGezag',
                        'bg_gemeente': 'GemeenteBevoegdGezag',
                        'INSTELLINGSNAAM': "NaamInstelling",
                        'PLAATSNAAM': "Plaats",
                        'TYPE MBO': "TypeMBO",
                        'KWALIFICATIENIVEAU': "Kwalificatieniveau",
                        'KWALIFICATIE CODE': "Kwalificatiecode",
                        'KWALIFICATIE NAAM': "Kwalificatienaam",
                        'MBO SECTOR': "MBOsector",
                        'DOMEIN': "Domein",
                        'SECTORUNIT SBB': "SectorUnitSBB",
                        'BRIN NUMMER KENNISCENTRUM': "BrinKenniscentrum",
                        'NAAM KENNISCENTRUM': "NaamKenniscentrum",
                        'GEMEENTENAAM VESTIGING': 'GemeenteVestiging',
                        'PROVINCIE VESTIGING': 'ProvincieVestiging',
                        'LEERWEG VMBO': 'LeerwegVMBO',
                        'VMBO SECTOR': 'VMBOsector',
                        'AFDELING': 'Afdeling', 
                        'EXAMENKANDIDATEN': 'Examenkandidaten',
                        'GESLAAGDEN': 'Geslaagden',
                        'GEZAKTEN': 'Gezakten',
                        'GEMIDDELD CIJFER SCHOOLEXAMEN': 'GemiddeldCijferSchoolexamen',
                        'GEMIDDELD CIJFER CENTRAAL EXAMEN': 'GemiddeldCijferCentraalExamen',
                        'GEMIDDELD CIJFER CIJFERLIJST': 'GemiddeldCijferCijferlijst'
                        }
